# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

service: ftct-dashboard-fe

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "us-east-1"}
  logRetentionInDays: 30
  deploymentBucket:
    name: us.expand.serverless.deployment.${self:custom.stage}
    serverSideEncryption: AES256

plugins:
  - serverless-s3-sync
  - serverless-s3-encryption

custom:
  stage: ${opt:stage, self:provider.stage}
  assetsBucket: ftct-dashboard-fe-${self:custom.stage}
  s3Sync:
    - bucketName: ${self:custom.assetsBucket}
      deleteRemoved: true
      localDir: build
      defaultContentType: text/html
      params:
        - index.html:
            CacheControl: "no-cache"
        - "*.js":
            CacheControl: "public, max-age=31536000"
      bucketTags:
        CostCenter: ${opt:costCenter,'12751-21'}
        Owner: pauline.wray@expandresearch.com
        TechnicalOwner: luke.budesha@expandresearch.com
        Service: AWS-ABM-ftct-dashboard-fe-${self:custom.stage}
        Application: ftct-dataPlatform-dashboard
        Environment: ${self:custom.stage}
  # Commented out when removing s3 bucket references in deployment.
  # s3-encryption:
  #   buckets:
  #     AssetsBucket:
  #       SSEAlgorithm: AES256
  domains:
    prod: fctdataplatform.bcg.com
    dev: dev.fct.bcgp.io
    test: test.fct.bcgp.io
  domainName: ${self:custom.domains.${self:custom.stage}, self:custom.domains.test}

resources:
  - ${file(resources/cloudfront-distribution-${opt:stage, self:custom.stage}.yml)}
